name: Emra Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_run:
    workflows: ["Build Base Docker Image"]
    types:
      - completed

jobs:
  code_analyze:
    name: 🔍 Code Quality Check (ESLint)
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

    outputs:
      lint_status: ${{ job.status }}
  build_docker:
    name: 🐳 Build Docker Image
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_custom_docker == 'true' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t playwright-custom:${{ github.sha }} .

    outputs:
      docker_image: playwright-custom:${{ github.sha }}

  autotest:
    name: 🧪 Run Playwright Testing
    runs-on: ubuntu-latest
    needs: build_docker

    container:
      image: ${{ needs.build_docker.outputs.docker_image }}

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - uses: actions/checkout@v4
    
      - name: Run tests
        run: npx playwright test